require("vuongtran.plugins-setup")
require("vuongtran.core.options")
require("vuongtran.core.keymaps")
require("vuongtran.core.colorscheme")
require("vuongtran.plugins.comment")
require("vuongtran.plugins.nvim-tree")
require("vuongtran.plugins.lualine")
require("vuongtran.plugins.telescope")
require("vuongtran.plugins.nvim-cmp")
require("vuongtran.plugins.lsp.mason")
require("vuongtran.plugins.lsp.lspsaga")
require("vuongtran.plugins.lsp.lspconfig")
require("vuongtran.plugins.lsp.null-ls")
require("vuongtran.plugins.autopairs")
-- require("vuongtran.plugins.treesitter")
require("vuongtran.plugins.gitsigns")
require("vuongtran.plugins.aucmd")
